[versions]
paper-api = "26.1.2.build.+"
minecraft = "26.1.2"
run-task = "3.0.2"
packetevents = "2.12.0"
adventure = "4.26.1"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
packetevents-spigot = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
